[package]
  cjc-version = "1.0.5"
  name = "cjh"
  description = "nothing here"
  version = "1.3.1"
  target-dir = ""
  output-type = "executable"
  bin-name = "cjh"
  compile-option = "--static --static-std --static-libs"
  override-compile-option = "--static --static-std --static-libs"
  link-option = "--disable-new-dtags -rpath /root/.cangjie/stdx/cangjie-stdx-linux-x64-1.0.5.1/static/stdx -rpath /opt/cangjie/cangjie/runtime/lib/linux_x86_64_cjnative -rpath /opt/cangjie/cangjie/third_party/llvm/lib -rpath /opt/cangjie/cangjie/lib/linux_x86_64_cjnative"
  package-configuration = {}

[dependencies]
  cjterm = { path = "./libs/cjterm" }
  cjllm = { path = "./libs/cjllm" }
  cjcfg = { path = "./libs/cjcfg" }
  cjutil = { path = "./libs/cjutil" }
  cjlog = { path = "./libs/cjlog" }

[target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["/root/.cangjie/stdx/cangjie-stdx-linux-x64-1.0.5.1/static/stdx"]

# Windows 交叉构建（cjc --target x86_64-pc-windows-gnu；stdx 静态链接）
[target.x86_64-pc-windows-gnu.bin-dependencies]
    path-option = ["/root/.cangjie/stdx/cangjie-stdx-windows-x64-1.0.5.1/windows_x86_64_cjnative/static/stdx"]
